-- Template only: review account, region, object names, and credit budget first.
-- This does NOT deploy a service or start the initially suspended compute pool.
USE ROLE ACCOUNTADMIN;
CREATE ROLE IF NOT EXISTS EWASTE_DEPLOYER;
CREATE ROLE IF NOT EXISTS EWASTE_API_CLIENT;
CREATE DATABASE IF NOT EXISTS EWASTE_ML;
CREATE SCHEMA IF NOT EXISTS EWASTE_ML.APP;
CREATE IMAGE REPOSITORY IF NOT EXISTS EWASTE_ML.APP.IMAGES;
GRANT USAGE ON DATABASE EWASTE_ML TO ROLE EWASTE_DEPLOYER;
GRANT USAGE ON SCHEMA EWASTE_ML.APP TO ROLE EWASTE_DEPLOYER;
GRANT CREATE SERVICE ON SCHEMA EWASTE_ML.APP TO ROLE EWASTE_DEPLOYER;
GRANT READ, WRITE ON IMAGE REPOSITORY EWASTE_ML.APP.IMAGES TO ROLE EWASTE_DEPLOYER;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE EWASTE_DEPLOYER;
CREATE COMPUTE POOL IF NOT EXISTS EWASTE_API_POOL
  MIN_NODES = 1 MAX_NODES = 1 INSTANCE_FAMILY = CPU_X64_XS
  INITIALLY_SUSPENDED = TRUE AUTO_RESUME = TRUE AUTO_SUSPEND_SECS = 300;
GRANT USAGE, MONITOR ON COMPUTE POOL EWASTE_API_POOL TO ROLE EWASTE_DEPLOYER;
GRANT USAGE ON DATABASE EWASTE_ML TO ROLE EWASTE_API_CLIENT;
GRANT USAGE ON SCHEMA EWASTE_ML.APP TO ROLE EWASTE_API_CLIENT;
-- Admin: replace names below, then execute these grants separately.
-- GRANT ROLE EWASTE_DEPLOYER TO USER <deployment_user>;
-- GRANT ROLE EWASTE_API_CLIENT TO USER <backend_service_user>;
SHOW IMAGE REPOSITORIES IN SCHEMA EWASTE_ML.APP;
